### ISSUE TITLE
Update connectors not working as expected

### ISSUE THREAD

**Issue by ssvaidyanathan** [GoogleCloudPlatform/application-integration-management-toolkit#123]
- Created a connector successfully using the console
- Stored the connector.json using the `integrationcli connectors get` command
- Updated the host info and ran the `integrationcli connectors update` command
- Command fails with the following error
```
Error: Bad Request - malformed request syntax: {
  "error": {
    "code": 400,
    "message": "The request was invalid: update_mask contains invalid fields",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "update_mask"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.RequestInfo",
        "requestId": "1077ae27d9d651cf"
      }
    ]
  }
}
```

**Comment by srinandan** [comment]
I tested the command and it worked fine. I suspect the `update_mask` flag wasn't properly set. In your example, the `update_mask` will be `destinationConfigs`

**Comment by ssvaidyanathan** [comment]
Worked as expected when I passed the update_mask
Maybe we should be more clear on the documentation on what to pass for `update_mask`

**Comment by kondurure** [comment]
@srinandan, can you please help me share share some samples for how should pass/use update_mask

**Comment by srinandan** [comment]
Sorry for the late reply. Here is an example:

```
integrationcli connectors update -n sample --update-mask=destinationConfigs,description,nodeConfig -f path/to/file.json -t $token -r $region -p $project
```

**Comment by srinandan** [comment]
I have submitted a PR which will set a default update mask so you don't have to pass anything.
