### ISSUE TITLE
errorCatcherConfigs not exporting via Scaffold and deployment of integrations is failing if we have errorCatcherConfigs 

### ISSUE THREAD

**Issue by kondurure** [GoogleCloudPlatform/application-integration-management-toolkit#127]
We have setup an Apigee Integration, with the use of Error Catcher. We found that the errorCatcherConfigs can't be exported via scaffold action. 
--------------------errorCatcherConfigs -------------
  "errorCatcherConfigs": [{
    "label": "Save PII error catcher",
    "errorCatcherNumber": "1",
    "startErrorTasks": [{
      "taskId": "5"
    }],
    "position": {
      "x": 420,
      "y": -882
    },
    "errorCatcherId": "SavePii_errorCatcher"
  }],
------------------------------------------

Exported Apigee Integration via Apigee Console and it has errorCatcherConfigs , but integration deployment failing with below error (complaining missing errorCatcherConfigs).

{
  "error": {
    "code": 400,
    "message": "Task with name Build Retrieval payload does not have an incoming edge from either task or trigger. Please connect the task to another task or a trigger by hovering the cursor over the outgoing edge of another task/trigger and dragging the edge to this task.",
    "status": "INVALID_ARGUMENT"
  }
}

Error: Bad Request - malformed request syntax: {
  "error": {
    "code": 400,
    "message": "Task with name Build Retrieval payload does not have an incoming edge from either task or trigger. Please connect the task to another task or a trigger by hovering the cursor over the outgoing edge of another task/trigger and dragging the edge to this task.",
    "status": "INVALID_ARGUMENT"
  }
}

scaffold command:
---------------------
/home/runner/.integrationcli/bin/integrationcli integrations scaffold -n ${{ inputs.integration-name }}  -s ${{ inputs.version }} -f ${{ inputs.version }}

**Comment by srinandan** [comment]
I see error config is available in the code (at least v0.69). Are you using v0.69?

**Comment by kondurure** [comment]
yes, integrationcli version 0.69.1-beta date: 2023-05-03T00:17:05Z [commit: 6270099]

**Comment by kondurure** [comment]
@srinandan , can you please help me on this  errorCatcherConfigs issue

**Comment by kondurure** [comment]
Still have the same issue with export with errorCatcherConfigs with [v0.69]
