### ISSUE TITLE
Integration export is working as expected with errorCatcherConfigs but deployment failing with below error if error cache ID refer inside other integration tasks.

### ISSUE THREAD

**Issue by kondurure** [GoogleCloudPlatform/application-integration-management-toolkit#131]
Thanks @srinandan. export is working as expected with errorCatcherConfigs but deployment failing with below error if error cache ID refer inside other integration tasks.

integrationcli version: v0.70.1-beta

ERROR: 2023/09/14 14:42:07 httpclient.go:129: error parsing response:  unexpected end of JSON input
Publish integration hl-shared-retry-failure-integration with version a55c3dbd-6203-4f50-8afa-5c6dc574629a
{
  "error": {
    "code": 400,
    "message": "Tasks in normal workflow can not be used as start error tasks for another normal task JavaScriptTask",
    "status": "INVALID_ARGUMENT"
  }
}

Error: Bad Request - malformed request syntax: {
  "error": {
    "code": 400,
    "message": "Tasks in normal workflow can not be used as start error tasks for another normal task JavaScriptTask",
    "status": "INVALID_ARGUMENT"
  }
}

_Originally posted by @kondurure in https://github.com/GoogleCloudPlatform/application-integration-management-toolkit/issues/127#issuecomment-1719613451_
            
![image](https://github.com/GoogleCloudPlatform/application-integration-management-toolkit/assets/106219615/63e8faa0-c8a6-4390-b634-637709256737)

**Comment by srinandan** [comment]
I have a candidate fix. We will publish a new beta release
