### ISSUE TITLE
Integration creation failing with an error "Integration cannot be run/published with connector task associated with different project. 

### ISSUE THREAD

**Issue by kondurure** [GoogleCloudPlatform/application-integration-management-toolkit#147]
Integration creation failing with an error "Integration cannot be run/published with connector task associated with different project. 

{
  "error": {
    "code": 400,
    "message": "Integration cannot be run/published with connector task associated with different project. Expected connector from project g-qa-1-s5-herbalife1-proj",
    "status": "INVALID_ARGUMENT"
  }
}

Error: Bad Request - malformed request syntax: {
  "error": {
    "code": 400,
    "message": "Integration cannot be run/published with connector task associated with different project. Expected connector from project g-qa-1-s5-herbalife1-proj",
    "status": "INVALID_ARGUMENT"
  }
}

INTEGRATIONCLI_VERSION=v0.70
Script:
---------
          export INTEGRATIONCLI_VERSION=v0.70
          curl -L https://raw.githubusercontent.com/GoogleCloudPlatform/application-integration-management-toolkit/main/downloadLatest.sh | sh -
          /home/runner/.integrationcli/bin/integrationcli -v
          /home/runner/.integrationcli/bin/integrationcli token cache -t $token > /tmp/logs.txt
          /home/runner/.integrationcli/bin/integrationcli prefs set --proj=${{ inputs.organization }} 
          if [ "${{ inputs.region }}" == "europe-west1" ]; then
            echo "Integration deploy in ${{ inputs.region }}"
            /home/runner/.integrationcli/bin/integrationcli integrations create -n ${{ inputs.integration_name }} -f ${{ github.workspace }}/src/${{ inputs.integration_name }}.json -u $SHORT_SHA -o ${{ github.workspace }}/overrides/${{ inputs.deploy_environment }}/overrides-weu.json -r ${{ inputs.region }} > /tmp/response
          else
            echo "Integration deploy in ${{ inputs.region }}"
            /home/runner/.integrationcli/bin/integrationcli integrations create -n ${{ inputs.integration_name }} -f ${{ github.workspace }}/src/${{ inputs.integration_name }}.json -u $SHORT_SHA -o ${{ github.workspace }}/overrides/${{ inputs.deploy_environment }}/overrides.json -r ${{ inputs.region }} -v > /tmp/response
          fi 
          echo "integration creation"
          echo "integration response: " $(cat /tmp/response)
          basename $(cat /tmp/response | jq -r .name) > /tmp/version
          echo "integration version: " $(cat /tmp/version)
          
          /home/runner/.integrationcli/bin/integrationcli integrations versions publish -n ${{ inputs.integration_name }} -v $(cat /tmp/version)

**Comment by ssvaidyanathan** [comment]
@kondurure - can this be closed?
