### ISSUE TITLE
API Call doesn't return error code 500, when integration application is already deleted

### ISSUE THREAD

**Issue by nuno-m-pereira-alb** [GoogleCloudPlatform/application-integration-management-toolkit#149]
There is a case when we deleted an integration and we need to check what happen, if we deleted the same integration. In this case, API Call doesn't return error **_code 500_**. **_Code 200_** is returned **when an Integration Apigee is already deleted**.

**Comment by ssvaidyanathan** [comment]
@nuno-m-pereira-alb - Thanks for raising this. We will look into this issue. This is not returned by the tool but the underlying API itself. Will update once we have it fixed

**Comment by nuno-m-pereira-alb** [comment]
Good afternoon, @ssvaidyanathan May you give an any idea when we have some news these about it, please?

**Comment by ssvaidyanathan** [comment]
@nuno-m-pereira-alb - I'll provide an update as soon as I hear from the team. There is a freeze at this time of the year so things gets pushed relatively slower.

**Comment by ssvaidyanathan** [comment]
@nuno-m-pereira-alb - the fix has been pushed. Can you please try it out and close the issue if its resolved?

**Comment by ssvaidyanathan** [comment]
Closing this issue as the fix is pushed. Please reopen if you see otherwise
