### ISSUE TITLE
Default values of the integration integer variable is not extracting with scaffold

### ISSUE THREAD

**Issue by kondurure** [GoogleCloudPlatform/application-integration-management-toolkit#189]
Default values of the integration integer variable is not extracting with scaffold from Dev environments.

Defined Integer values as below in Dev environment but with scaffold default value of integer datatype is empty but if I download from Dev environment manual, integer value is as expected.

Defined in Dev env:
![image](https://github.com/GoogleCloudPlatform/application-integration-management-toolkit/assets/106219615/7de2252e-ab12-48a5-9f8a-d7bb99ad5c57)

Screenshot from scaffold output:
![image](https://github.com/GoogleCloudPlatform/application-integration-management-toolkit/assets/106219615/90add808-4744-407c-83f0-5e3f9b516d67)

with manual extracted src file, even integration deploy also reflecting as empty in higher environments.

**Comment by ssvaidyanathan** [comment]
Fixed and Released in v0.74.2

**Comment by kondurure** [comment]
Thanks @ssvaidyanathan  and @srinandan
