### ISSUE TITLE
integrationcli integrations versions publish failing with no such file or directory error

### ISSUE THREAD

**Issue by Sarmistha91** [GoogleCloudPlatform/application-integration-management-toolkit#230]
command - 
integrationcli integrations versions publish -t=${{ steps.auth.outputs.access_token}} -p=${{ vars.GCP_PROJECT }} -r=${{ vars.GCP_REGION }} -n=$env_integration_name -s=$env_snap_shot_number

All these variables are getting populated and the snapshot is also created in Apigee but the publish/deploy is failing with error **Error: stat : no such file or directory**

**Comment by ssvaidyanathan** [comment]
@Sarmistha91 - which version are you using?

**Comment by srinandan** [comment]
There is a bug, I will create a fix soon.

**Comment by ssvaidyanathan** [comment]
We just released `0.75.1`, can you please try with the latest version and let us know

**Comment by Sarmistha91** [comment]
Thanks for the quick help.  This helped the deployment .
