### ISSUE TITLE
Unable to provide Config variable for pub sub trigger service account

### ISSUE THREAD

**Issue by Sarmistha91** [GoogleCloudPlatform/application-integration-management-toolkit#249]
Tried below approaches to add the same -

- Created a config-variables folder and added the file config.json
- Included the below details -
{
"`CONFIG_pubSubSA`": "#value"
}
- And added the command in the publish statement
- integrationcli integrations versions publish -t=${{ steps.auth.outputs.access_token}} -p=${{ vars.GCP_PROJECT }} -r=${{ vars.GCP_REGION }} -n=$env_integration_name -s=$env_snap_shot_number --config-vars=config-variables/config.json

The integration folder contains a json file (which is extracted from server) which contains a different CONFIG_pubSubSA (for lower env). 
While publishing, the integration still picks up the contents of the json file and not getting replaced by the value defined in the file config.json under folder config-variables

Failed with error -
{
  "error": {
    "code": 400,
    "message": "Failed while deploying Cloud Pubsub Trigger for integration cicd-dev-test-intergration. Reason: Necessary roles might be missing for Cloud Pub/Sub Trigger. For more information, see ([https://cloud.google.com/application-integration/docs/configure-pubsub-trigger#iam-roles)."](https://cloud.google.com/application-integration/docs/configure-pubsub-trigger#iam-roles).%22),
    "status": "FAILED_PRECONDITION"
  }
}

**Comment by Sarmistha91** [comment]
@ssvaidyanathan  - Version used - v0.76.0

We were able to override the values using overrides.json but we want to explore the option of Config variable as well to be able to update the details directly in config files without disturbing the integration.json file.

**Comment by ssvaidyanathan** [comment]
@Sarmistha91 - you should use the "scaffold" option that will pull everything including the overrides and config variables.

**Comment by srinandan** [comment]
It appears these issues are resolved. I'm closing them. If that's not the case, reopen it with the information @ssvaidyanathan asked for.
