### ISSUE TITLE
[FR] Allow to skip authconfigs by scaffolding too

### ISSUE THREAD

**Issue by teliatko** [GoogleCloudPlatform/application-integration-management-toolkit#254]
**Is your feature request related to a problem? Please describe.**
By scaffolding the connectors can be skipped, but authconfigs cannot be. This way authconfigs are duplicated.

**Describe the solution you'd like**
Add flag `--skip-authconfigs` to allow skip them.

**Describe alternatives you've considered**

**Additional context**
The use-case is where the auth configs are shared across integrations. 
Let's say integration `A` makes REST requests to system `X` using `basic auth`. But, in the same GCP project integrations `B` , `C` and `D` are also making calls to `X` using the same auth mechanism. 
In such scenario is desired to have just one authconfig in one place and be able to skip it in integrations. Of course in such setup one have to apply authconfig first and then integrations.

**Comment by ssvaidyanathan** [comment]
Released in [v0.76.2](https://github.com/GoogleCloudPlatform/application-integration-management-toolkit/tree/v0.76.2)

**Comment by ssvaidyanathan** [comment]
Released in [v0.76.2](https://github.com/GoogleCloudPlatform/application-integration-management-toolkit/tree/v0.76.2)
