### ISSUE TITLE
[BUG] scaffold is not extracting the variable Masking in Apigee Integration.

### ISSUE THREAD

**Issue by kondurure** [GoogleCloudPlatform/application-integration-management-toolkit#256]
**Describe the bug**
with scaffold integration masking gets exporting correctly but variable level masking is not exporting with manual extract exporting both masking parameters.

**Version**
integrationcli_v0.74.2

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
variable level masking is not exporting with scaffold 

**Screenshots**
with scaffold export:
![image](https://github.com/GoogleCloudPlatform/application-integration-management-toolkit/assets/106219615/fc68cd4d-ebfb-4702-8d80-dedd6f337abb)

with manual export:
![image](https://github.com/GoogleCloudPlatform/application-integration-management-toolkit/assets/106219615/cde776ba-3f09-4b17-908d-3026beb92d51)

**Additional context**

**Comment by ssvaidyanathan** [comment]
@kondurure - I think you have the same screenshot
Can you please update the correct one so that we can see the difference

**Comment by kondurure** [comment]
it's my bad, here the correct screen shot for manual export 
![image](https://github.com/GoogleCloudPlatform/application-integration-management-toolkit/assets/106219615/710405d6-cb9b-49d0-ba33-b00c65446e7c)

**Comment by ssvaidyanathan** [comment]
Released in [v0.76.2](https://github.com/GoogleCloudPlatform/application-integration-management-toolkit/tree/v0.76.2)
