### ISSUE TITLE
[FR] Support failure policy on data mapper tasks

### ISSUE THREAD

**Issue by meghangupte** [GoogleCloudPlatform/application-integration-management-toolkit#314]
**Is your feature request related to a problem? Please describe.**
It is possible to have a failure policy on the data mapper task. However, it is not supported as part of the  integrationcli `scaffold` command.
version - integrationcli version 0.77.0 date: 2024-11-13T17:33:30Z [commit: 77ba4c7]

**Describe the solution you'd like**
Add support for failure policy in the scaffold command

**Describe alternatives you've considered**

**Additional context**
Failure policy is part of error handling. It lets you decide how you want to handle errors in case there is any error during data mapping. 
<img width="404" alt="Screenshot 2024-12-09 at 4 06 24 PM" src="https://github.com/user-attachments/assets/9754ef77-f5b8-4d3c-8d0f-c85b6a5fcbb0">

When I try to scaffold the integration as part of the ci/cd process, it it doesn't include the failure policy. However, when I manually download the integration I can see the failure policy
```"conditionalFailurePolicies": {
      "failurePolicies": [{
        "retryStrategy": "FIXED_INTERVAL",
        "maxRetries": 2,
        "intervalTime": "1970-01-01T00:00:30Z",
        "condition": "$`ExecutionMode`$ \u003d SYNC"
      }, {
        "retryStrategy": "FIXED_INTERVAL",
        "maxRetries": 2,
        "intervalTime": "1970-01-01T00:00:30Z",
        "condition": "$`ExecutionMode`$ \u003d ASYNC"
      }],
      "defaultFailurePolicy": {
        "retryStrategy": "RESTART_INTEGRATION_WITH_BACKOFF",
        "maxRetries": 2,
        "intervalTime": "1970-01-01T00:00:30Z"
      }
    }```

**Comment by ssvaidyanathan** [comment]
Fixed and released in `v0.78.0`
