### ISSUE TITLE
[BUG] integrationcli integrations versions list gives me a giant ball of json

### ISSUE THREAD

**Issue by DinoChiesa** [GoogleCloudPlatform/application-integration-management-toolkit#328]
## Summary
The command to list the versions of a named integration gives me ... a giant ball of JSON, that I do  not want.  I need to scroll back 1500 lines to see if I can detect a version number anywhere in there.  (spoiler: I can't) 

If integrationcli is intended for interactive and scripting use,  a command like `integrationcli integrations versions list` should display a list of uuids like  
```
[ 
 "e1a7be8a-8f52-45f5-ae61-e4a6355ec447",
 "c65234bd-5580-4f59-a8ed-587d167baf0d",
  ...
]
```
 or similar.

## Example of Actual behavior
```
$ integrationcli integrations versions list -n apigee-pdu-check-1 
{
        "integrationVersions": [
                {
                        "name": "projects/9115824783367/locations/us-west1/integrations/integration-name-1/versions/e1a7be8a-8f52-45f5-ae61-e4a63533c447",
                        "description": "description here.",
                        "origin": "UI",
                        "snapshotNumber": "1",
                        "updateTime": "2024-12-20T01:27:30.722Z",
                        "lockHolder": "person@example.com",
                        "createTime": "2024-12-20T01:27:30.722Z",
                        "lastModifierEmail": "person@google.com",
                        "state": "DRAFT",
                        "triggerConfigs": [
                                {
                                        "label": "Query Organization",
                                        "startTasks": [
                                                {
                               ...more than 1000 more lines...
```

## Desired behavior
the tool emits a brief list of integers. 

## More details

| Q | A | 
| -- | -- |
| Version | version 0.78.0 date: 2024-12-10T17:57:38Z [commit: 9371c4e] |
| To Reproduce | see above | 
| Expected behavior | the output of "list" should be a brief list of IDs. (The output of "GET" should be a large JSON blob.)|

**Comment by srinandan** [comment]
I wouldn't describe this behavior as a bug, perhaps an enhancement. 

The CLI is a wrapper around the APIs (with some exceptions). The AIP standards for Google APIs require that a list returns an array of (full) objects and not simply the IDs.

Proposed change - Introduce new flags to return a list of IDs or user labels or snapshot numbers. Default behavior will continue to return a enormous JSON.
